apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-eventlistener-route
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: el-{{ .Release.Name }}-eventlistener
    weight: 100
  wildcardPolicy: None
