apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-app-config
    app.kubernetes.io/name:  {{ .Release.Name }}-app-config
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-app-config
  namespace: {{ .Release.Namespace }}  
data:
  APP_NAME: "{{ .Release.Name }}"
  APP_NAMESPACE: "{{ .Release.Namespace }}"
  QUAY_SECRET_NAME: "{{ .Values.tekton.quaySecretName}}"
  GIT_TOKEN_KEY: "{{ .Values.tekton.gitSecretKeyToken }}"
  GIT_SECRET_NAME: "{{ .Values.tekton.gitSecretName }}"
