apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}-sa
    app.kubernetes.io/name:  {{ .Release.Name }}-sa
    app.kubernetes.io/part-of: {{ .Release.Name }}
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}  
