---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Release.Name }}-openshift-pipelines-operator
  namespace: openshift-operators
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name:  {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  channel: pipelines-1.16
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace