name: Lint

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # pin@v4.2.0
        with:
          version: v3.10.0

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # pin@v4
        with:
          python-version: 3.12

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # pin@v2.3.0

      - name: Run chart-testing (lint)
        run: ct lint --config .ct/config.yaml
